core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('supplies.urls', namespace='supplies')),
    path('device/', include('device.urls', namespace='device')),
    path('reports/', include('reports.urls', namespace='reports')),
    # extends    
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

device/urls.py
from django.urls import path
from .views import (
    homeView,
    GroupDeviceListView,
    DeviceListView,
    SuppliesOfDeviceListView,
)

app_name = 'device'
urlpatterns = [
    path('', homeView, name='home'),
    path('groupdevice-view/', GroupDeviceListView.as_view(), name='groupdevice-view'),
    path('list-device/<pk>', DeviceListView.as_view(), name='list-device'),
    path('list-supplies/<pk>', SuppliesOfDeviceListView.as_view(), name='list-supplies'),
]

device/models.py
from django.db import models
from django.shortcuts import reverse
from units.models import Units
from supplies.models import Supplies
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField
# Create your models here.


class ItemBase(models.Model):
    # Khai báo lơp Meta để không tạo ra data trong cơ sở dữ liệu
    class Meta:
        abstract = True
    code = models.CharField(_('code'), max_length=30, unique=True, null=False)
    name = models.TextField(_('name'), null=False)
    created_date = models.DateTimeField(_('created_date'), auto_now_add=True)
    updated_date = models.DateTimeField(_('updated_date'), auto_now=True)
    active = models.BooleanField(_('active'), default=True)

    def __str__(self) -> str:
        return f"{self.code} - {self.name}"

# Nhóm thiết bị máy móc


class GroupDevice(ItemBase):
    description = RichTextField(_('description'), null=True)
    image = models.ImageField(_('image'),
                              upload_to='groupdevice/%Y/%m', default='No_image.png')

    class Meta:
        verbose_name_plural = "Nhóm thiết bị"

    '''
    Hàm gọi trả về danh sách thiết bị the khóa id của nhóm thiết bị
    
    '''

    def get_absolute_url(self):
        return reverse("device:list-device", kwargs={"pk": self.pk})
# Thiết bị máy móc


class Device(ItemBase):
    description = RichTextField(_('description'), null=True)
    group_device = models.ForeignKey(
        GroupDevice, on_delete=models.SET_NULL, null=True)
    units = models.ForeignKey(Units, on_delete=models.SET_NULL, null=True)
    supplies = models.ManyToManyField(Supplies)
    image = models.ImageField(
        _('image'), upload_to='device/%Y/%m', default='No_image.png')

    class Meta:
        verbose_name_plural = "Thiết bị"

    def get_absolute_url(self):
        return reverse("device:list-supplies", kwargs={"pk": self.pk})

device/forms.py
from logging import PlaceHolder
from tkinter import Widget
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import (
    GroupDevice,
    Device,
)


class GroupDeviceForms(forms.ModelForm):
    description = forms.CharField(widget=CKEditorUploadingWidget)

    class Meta:
        model = GroupDevice
        fields = "__all__"

    #def clean_code(self):
        # do something that validates your data
        #return self.cleaned_data["code"]


class DeviceForms(forms.ModelForm):
    description = forms.CharField(widget=CKEditorUploadingWidget)

    class Meta:
        model = Device
        fields = "__all__"

    #def clean_code(self):
        # do something that validates your data
        #return self.cleaned_data["code"]
class DeviceSearchForm(forms.Form):
    text_input = forms.CharField(label=False, widget=forms.TextInput(attrs={
        "type":"text",
        "class":"form-control",
        "placeholder":"Nhập thông tin (mã vật tư hoặc tên vật tư) cầm tìm kiếm"
    }))
        

device/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from .forms import GroupDeviceForms, DeviceSearchForm
from .models import (
    GroupDevice,
    Device,
)
# Create your views here.


def homeView(request):
    template_name = 'device/home.html'
    context = {'name': "Xin chao Device",
               'form':DeviceSearchForm( request.POST or None)
               } 
       
    return render(request, template_name, context)

class GroupDeviceListView(ListView):
    model = GroupDevice
    template_name = 'device/groupdevices-view.html'
    context_object_name = 'groupdevices'

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = GroupDevice.__name__        
        return context

    def get_queryset(self):
        return GroupDevice.objects.filter(active=True)


class DeviceListView(ListView):
    model = Device
    template_name = 'device/list-device.html'
    #context_object_name = 'device'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Device.__name__
        return context

    def get_queryset(self):
        return Device.objects.filter(group_device=self.kwargs['pk'])


class SuppliesOfDeviceListView(ListView):
    model = Device
    template_name = 'device/list-supplies-device.html'
    context_object_name = 'device'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        device = Device.objects.get(pk=self.kwargs['pk'])
        #context["device"] = device
        context["supplies"] = device.supplies.all()
        return context

    def get_queryset(self):
        return Device.objects.get(pk=self.kwargs['pk'])

templates/device/groupdevice-view.html
{% extends 'base.html' %} 
{% block title %}
    {{title}}
{%endblock title %} 
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for obj in groupdevices %}
          <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="text-center">Mã vật tư: {{obj.code}}.</div>
                    <div class="text-center">Tên vật tư: {{obj.name}}.</div>                    
                </div>              
                <img src="/media/{{obj.image}}" alt="{{obj.name}}" width='100%' height="250px">
                <div class="card-body">
                   <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group mt-3">
                      <button type="button" class="btn btn-sm btn-outline-secondary"><a href={{ obj.get_absolute_url }}>View</a></button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">{{obj.updated_date}}</small>
                </div> 
                </div>                
            </div>
          </div>
          {% endfor %}
        </div>
    </div>
</div>
<div class="row">
  <div class="col-12">
      <span class="step-links">
          {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
</div>
{% endblock content %}

templates/device/home.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- favicon -->
        <link rel="shortcut icon" href=" {% static 'favicon.ico' %} ">
        <title>Equipment | {% block title %}{% endblock title %} </title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Dropzone js -->        
        
        <link rel="stylesheet" href="{% static 'dropzone/dropzone.min.css' %}">
        <!-- Custom js & css -->
        <link rel="stylesheet" href="{% static 'mystyle/style.css' %}">
        
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
                               
        <div class="container">
            <div class="row justify-content-md-center" >
              <div class="col-md-auto ">
                <span><img src="/media/logo/logo-dam.png" alt="" width="200px"></span>
              </div>                  
            </div>
            <div class="row justify-content-md-center bg-light p-3" >
                <div class="col-md-auto">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="input-group mb-3">            
                        {{form|crispy}}
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <button class="btn btn-primary" type="submit"> <img src="/media/logo/logo-dam.png" alt="Tìm kiếm" width="20px"> </button>                        
                    </div>
                    </form>
                    
                </div>                  
              </div>                
        </div>
        <!-- Bootstrap js -->
        <script src="{% static 'dropzone/dropzone.min.js'  %}" async defer></script>
        <script src="{% static 'popper/popper.min.js' %}" async defer></script>
        <script src="{% static 'js/bootstrap.min.js' %}" async defer ></script>    
        <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous" async defer></script>
        <script src="{% static 'jquery/jquery-3.6.0.min.js'  %}" async defer></script>
        <script src="{% static 'jquery/jquery.bootstrap.modal.forms.js' %}" async defer></script>
        <!-- You can alternatively load the minified version -->
        <script src="{% static 'jquery/jquery.bootstrap.modal.forms.min.js' %}"></script>
        
        {% block scripts %}{% endblock scripts %}
        <script src="" async defer></script>
    </body>
</html>

templates/device/list-device.html
{% extends 'base.html' %} 
{% block title %}
    List Device
{%endblock title %} 
{% block content %}
<div class="card-group">
    <div class="d-flex align-items-center">
        <div class="flex-shrink-0">
          <img src="/media/{{groupdevice.image}}" alt="..." width='300px'>
        </div>
        <div class="flex-grow-1 ms-3">
          <ul>
              <li>Mã thiết bị: {{groupdevice.code}} </li>
              <li>Tên thiết bị thiết bị: {{groupdevice.name}} </li>
          </ul>
        </div>
        
      </div>
    <h1>Danh sách thiết bị thuộc nhóm:</h1>

    <div class="card-group mt-3">
        <div class="row">
            {% for obj in object_list %}
            <div class="col-md-4">
                <div class="card">
                    <img src="/media/{{obj.image}}" class="card-img-top" alt="..." width='50px'>
                    <div class="card-body">
                    <h5 class="card-title">Mã thiết bị: {{obj.code}}</h5>                
                    <h5 class="card-title">Tên thiết bị: <a href=" {{obj.get_absolute_url}} ">{{obj.name}}</a>  </h5>                    
                    <p>
                        <a class="btn btn-primary" data-bs-toggle="collapse" href="#{{obj.code}}" role="button" aria-expanded="false" aria-controls="{{obj.code}}">
                        Mô tả
                        </a>
                    </p>
                    <div class="collapse" id="{{obj.code}}">
                        <div class="card card-body">
                            {{obj.description|safe}}
                        </div>
                    </div>
                    <p class="card-text"><small class="text-muted">Ngày cập nhật: {{obj.updated_date}}</small></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>        
    </div>
    
{% endblock content %}

templates/device/list-groupdevices.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{%endblock title %} 
{% block content %}

<div class="accordion" id="accordionExample">
  {% for group in groupDevices %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne"> 
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne-{{group.id}}" aria-expanded="true" aria-controls="collapseOne">
        <h5><a href={{ group.get_absolute_url }}>{{group.name}}</a> </h5>
      </button>          
    </h2>
    <div id="collapseOne-{{group.id}}" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">          
            {% for supp in group.device_set.all %}
            <div class="col">
              <div class="card shadow-sm">              
                <img src="/media/{{supp.image}}" alt="{{supp.name}}" width='100%' height="225px">
                <div class="card-body">
                    <div class="text-center">Mã thiết bị: {{supp.code}}.</div>
                    <div class="text-center">Tên thiết bị: {{supp.name}}.</div>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group mt-3">
                      <button type="button" class="btn btn-sm btn-outline-secondary"><a href="">View</a></button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}  
</div>
{% endblock content %}

templates/device/list-supplies-device.html
{% extends 'base.html' %} 
{% block title %}
    {{device.name}}
{%endblock title %} 
{% block content %}
    
    <div class="card-group">
        <div class="d-flex align-items-center">
            <div class="flex-shrink-0">
              <img src="/media/{{device.image}}" alt="..." width='300px'>
            </div>
            <div class="flex-grow-1 ms-3">
              <ul>
                  <li>Mã thiết bị: {{device.code}} </li>
                  <li>Tên thiết bị thiết bị: <b>{{device.name}} </b>  </li>
              </ul>
            </div>
          </div>
          <hr>
          <h1>Danh sách vật tư có thể thay thế cho thiết bị:</h1>
        <div class="row mt-3">            
            {% for obj in supplies %}
            <div class="col-md-4">
                <div class="card">
                    <img src="/media/{{obj.image}}" class="card-img-top" alt="..." width='50px'>
                    <div class="card-body">
                    <h5 class="card-title">Mã vật tư: {{obj.code}}</h5>                
                    <h5 class="card-title">Tên vật tư: {{obj.name}} </h5>                    
                    <p>
                        <a class="btn btn-primary" data-bs-toggle="collapse" href="#{{obj.code}}" role="button" aria-expanded="false" aria-controls="{{obj.code}}">
                        Mô tả
                        </a>
                    </p>
                    <div class="collapse" id="{{obj.code}}">
                        <div class="card card-body">
                            {{obj.description|safe}}
                        </div>
                    </div>
                    <p class="card-text"><small class="text-muted">Ngày cập nhật: {{obj.updated_date}}</small></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>        
    </div>
    
{% endblock content %}