core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('supplies.urls', namespace='supplies')),
    path('device/', include('device.urls', namespace='device')),
    path('reports/', include('reports.urls', namespace='reports')),
    # extends    
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supplies/urls.py
from django.urls import path
from .views import (
    homeView,
    SuppliesDetailView,
    GroupSuppliesListView,
    SuppliesListView,
    SuppliesListViewByGroup,
)

app_name = 'supplies'
urlpatterns = [
    path('', homeView, name='home'),
    path('detail/<pk>/',SuppliesDetailView.as_view(),name='detail'),
    path('groupsupplies-view/', GroupSuppliesListView.as_view(), name='groupsupplies-view'),
    path('supplies-view/', SuppliesListView.as_view(), name='supplies-view'),
    path('list-supplies/<pk>/', SuppliesListViewByGroup.as_view(),name='list-supplies'),
]

supplies/models.py
from django.db import models
from django.shortcuts import reverse
from units.models import Units
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField

# Create your models here.


class ItemBase(models.Model):
    # Khai báo lơp Meta để không tạo ra data trong cơ sở dữ liệu
    class Meta:
        abstract = True

    code = models.CharField(_('code'), max_length=30, unique=True, null=False)
    name = models.TextField(_('name'), null=False)
    created_date = models.DateTimeField(_('created_date'), auto_now_add=True)
    updated_date = models.DateTimeField(_('updated_date'), auto_now=True)
    active = models.BooleanField(_('active'), default=True)

    def __str__(self) -> str:
        return self.name

# Nhóm vật tư


class GroupSupplies(ItemBase):
    description = RichTextField(null=True, verbose_name="Mô tả nhóm vật tư")
    image = models.ImageField(_('image'),
                              upload_to='groupsupplies/%Y/%m', default='No_image.png')

    class Meta:
        verbose_name_plural = "Nhóm vật tư"

    def get_absolute_url(self):
        return reverse("supplies:list-supplies", kwargs={"pk": self.pk})
# Chi tiết vật tư


class Supplies(ItemBase):
    description = RichTextField(null=True, verbose_name="Mô tả vật tư")
    group_supplies = models.ForeignKey(
        GroupSupplies, on_delete=models.SET_NULL, null=True, verbose_name="Nhóm vật tư")
    units = models.ForeignKey(
        Units, on_delete=models.SET_NULL, null=True, verbose_name="Đơn vị tính")
    image = models.ImageField(upload_to='supplies/%Y/%m', default='No_image.png')

    class Meta:
        verbose_name_plural = "Vật tư"
    
    def get_absolute_url(self):
        return reverse("supplies:detail", kwargs={"pk": self.pk})
    

supplies/forms.py
from pyexpat import model
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import (
    GroupSupplies,
    Supplies,
)


class GroupSuppliesFroms(forms.ModelForm):

    description = forms.CharField(widget=CKEditorUploadingWidget)

    class Meta:
        model = GroupSupplies
        fields = "__all__"
 
   

class SuppliesForms(forms.ModelForm):
    description = forms.CharField(widget=CKEditorUploadingWidget)

    class Meta:
        model = Supplies
        fields = "__all__"
   
class SuppliesSearchForm(forms.Form):
    text_input = forms.CharField(label=False, widget=forms.TextInput(attrs={
        "type":"text",
        "class":"form-control",
        "placeholder":"Nhập thông tin (mã vật tư hoặc tên vật tư) cầm tìm kiếm"
    }))

supplies/views.py
from django.db.models import Q
from django.views import View
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .forms import SuppliesSearchForm
from .models import (
    GroupSupplies,
    Supplies,

)
# Create your views here.


def homeView(request):
    template_name = 'supplies/home.html'
    queryset = None
    form = SuppliesSearchForm(request.POST or None)
    print(request.method)

    context = {'name': "Xin chao Device",
               'form': form,
               'supplies': queryset,
               'groups': GroupSupplies.objects.all(),
               }

    if request.method == 'POST':
        text_input = request.POST.get('text_input')
        queryset = Supplies.objects.filter(
            Q(code__icontains=text_input) |
            Q(name__icontains=text_input)
        ).distinct()
        print(queryset)

        context = {'name': "Xin chao Device",
                   'form': form,
                   'supplies': queryset,
                   'groups': GroupSupplies.objects.all(),
                   }

    return render(request, template_name, context)


class SuppliesDetailView(DetailView):
    model = Supplies
    template_name = 'supplies/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Supplies.__name__
        return context


class GroupSuppliesListView(ListView):
    model = GroupSupplies
    template_name = 'supplies/groupsupplies-view.html'
    context_object_name = "groupsupplies"
    paginate_by = 6
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = GroupSupplies.__name__
        return context

    def get_queryset(self):
        return GroupSupplies.objects.filter(active=True)


class SuppliesListView(ListView):
    model = Supplies
    template_name = 'supplies/supplies-view.html'
    context_object_name = 'supplies'
    paginate_by = 6   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Supplies.__name__
        return context

    def get_queryset(self):
        return Supplies.objects.filter(active=True)


class SuppliesListViewByGroup(ListView):
    model = Supplies
    template_name = 'supplies/list-supplies.html'
    context_object_name = 'gsupplies'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Supplies.__name__
        return context

    def get_queryset(self):
        return Supplies.objects.filter(group_supplies=self.kwargs['pk'])

templates/supplies/temp/home-temp.html
{% extends 'base.html' %} 
{% block title %}
    Home Supplies
{%endblock title %} 
{% block content %}
    <h1>Supplies</h1>
    <br>
    {{name}}

    <div class="card-group">
      
        <div class="row">
            {% for item in '12354789654788' %}
            <div class="col-md-4">
               <div class="card ">
                <img src="http://placeimg.com/640/480/any" class="card-img-top" alt="..." width="50px">
                <div class="card-body">
                <h5 class="card-title">Card title {{item}}</h5>
                <p class="card-text"> {% lorem 1 b random %}</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
            </div> 
            </div>
            {% endfor %}  
        </div>            
            
             
        
    </div>

{% endblock content %}

templates/supplies/temp/list-groupsupplies.html
{% extends 'base.html' %} 
{% block title %}
    {{title}}
{%endblock title %} 
{% block content %}

<div class="accordion" id="accordionExample">
  {% for group in groupsupplies %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne"> 
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne-{{group.id}}" aria-expanded="true" aria-controls="collapseOne">
        <h5><a href={{ group.get_absolute_url }}>{{group.name}}</a> </h5>
      </button>          
    </h2>
    <div id="collapseOne-{{group.id}}" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">          
            {% for supp in group.supplies_set.all %}
            <div class="col">
              <div class="card shadow-sm">              
                <img src="/media/{{supp.image}}" alt="{{supp.name}}" width='100%' height="225px">
                <div class="card-body">
                    <div class="text-center">Mã vật tư: {{supp.code}}.</div>
                    <div class="text-center">Tên vật tư: {{supp.name}}.</div>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group mt-3">
                      <button type="button" class="btn btn-sm btn-outline-secondary"><a href="">View</a></button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}  
</div>

{% endblock content %}

templates/supplies/temp/result.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    {{title}}
{%endblock title %} 
{% block content %}        
<div class="row justify-content-md-center" >
    <div class="col-md-auto ">
      <span><img src="{% static 'logo/logo-dam.png' %}" alt="" width="150px"></span>
    </div>                  
</div>
<div class="row justify-content-md-center p-3" >
      <div class="col-md-auto">
          <form action="." role="search" method="POST">
              {% csrf_token %}
              <div class="input-group mb-3">            
              {{form|crispy}}
              <div class="valid-feedback">
                  Looks good!
              </div>
              <button class="btn btn-primary" type="submit"> <img src="{% static 'logo/logo-dam.png' %}" alt="Tìm kiếm" width="20px"> </button>                        
          </div>
          </form>                    
      </div>                  
</div> 
{% if supplies %}
    <p>fsdfsf</p>
    <br  />
{% endif %}   
<div class="album py-5">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for supp in supplies %}
          <div class="col">
              <div class="card shadow-sm">              
              <img src="/media/{{supp.image}}" alt="{{supp.name}}" width='100%' height="225px">
              <div class="card-body">
                  <div class="text-center">Mã vật tư: {{supp.code}}.</div>
                  <div class="text-center">Tên vật tư: {{supp.name}}.</div>
                  <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group mt-3">
                      <button type="button" class="btn btn-sm btn-outline-secondary"><a href={{supp.get_absolute_url}}>View</a></button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                  </div>
              </div>
              </div>
          </div>
        {% endfor %}
    </div>
</div> 
{% endblock content %}