core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('supplies.urls', namespace='supplies')),
    path('device/', include('device.urls', namespace='device')),
    path('reports/', include('reports.urls', namespace='reports')),
    # extends    
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

device/urls.py
from django.urls import path
from .views import (
    homeView,
    GroupDeviceListView,
    DeviceListView,
    SuppliesOfDeviceListView,
)

app_name = 'device'
urlpatterns = [
    path('', homeView, name='home'),
    path('groupdevice-view/', GroupDeviceListView.as_view(), name='groupdevice-view'),
    path('list-device/<pk>', DeviceListView.as_view(), name='list-device'),
    path('list-supplies/<pk>', SuppliesOfDeviceListView.as_view(), name='list-supplies'),
]

supplies/urls.py
from django.urls import path
from .views import (
    homeView,
    SuppliesDetailView,
    GroupSuppliesListView,
    SuppliesListView,
    SuppliesListViewByGroup,
)

app_name = 'supplies'
urlpatterns = [
    path('', homeView, name='home'),
    path('detail/<pk>/',SuppliesDetailView.as_view(),name='detail'),
    path('groupsupplies-view/', GroupSuppliesListView.as_view(), name='groupsupplies-view'),
    path('supplies-view/', SuppliesListView.as_view(), name='supplies-view'),
    path('list-supplies/<pk>/', SuppliesListViewByGroup.as_view(),name='list-supplies'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- favicon -->
        <link rel="shortcut icon" href=" {% static 'favicon.ico' %} ">
        <title>Equipment | {% block title %}{% endblock title %} </title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Dropzone js -->        
        
        <link rel="stylesheet" href="{% static 'dropzone/dropzone.min.css' %}">
        <!-- Custom js & css -->
        <link rel="stylesheet" href="{% static 'mystyle/style.css' %}">
        
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">             
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/">Trang chủ</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'supplies:groupsupplies-view' %} ">Nhóm vật tư</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'supplies:supplies-view' %}">Vật tư</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href=" {% url 'device:groupdevice-view' %} ">Nhóm thiết bị</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="">thiết bị</a>
                </li>
                {% endif %}
                
                <!--
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled">Disabled</a>
                </li>
              </ul>
              <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form> 
                -->                  
            </div>
          </div>
        </nav>
        <div class="container">
            <div class="bg-transparent p-1 rounded">
                {% block content %}{% endblock content %}
            </div>
        </div>

        <footer class="text-center text-lg-start bg-light text-muted">
          <hr />
          <!-- Copyright -->
          <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Copyright:
            <a class="text-reset fw-bold" href="https://www.youtube.com/channel/UCEGWmhNZyn3Lm5ky9SQGPwA"> Lê Đồng Chung</a>
          </div>
          <!-- Copyright -->
        </footer>
        <!-- Bootstrap js -->
        <script src="{% static 'dropzone/dropzone.min.js'  %}" async defer></script>
        <script src="{% static 'popper/popper.min.js' %}" async defer></script>
        <script src="{% static 'js/bootstrap.min.js' %}" async defer ></script>    
        <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous" async defer></script>
        <script src="{% static 'jquery/jquery-3.6.0.min.js'  %}" async defer></script>
        <script src="{% static 'jquery/jquery.bootstrap.modal.forms.js' %}" async defer></script>
        <!-- You can alternatively load the minified version -->
        <script src="{% static 'jquery/jquery.bootstrap.modal.forms.min.js' %}"></script>
        
        {% block scripts %}{% endblock scripts %}
        <script src="" async defer></script>
    </body>
</html>